// *******************************************************************************
// Copyright (c) 2026 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache License Version 2.0 which is available at
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0
// *******************************************************************************

start: fd_model

fd_model: "package" fd_fqn f_imports* (fd_specification | fd_types)+

f_imports: _import{fd_imported_fqn}
fd_imported_fqn: _imported_fqn{fd_fqn}
fd_fqn: _fully_qualified_name{fd_valid_id}
fd_valid_id: _valid_id{fd_keywords}

fd_keywords: \
      "Boolean" | "Integer" | "Interface" | "String"
                | "array" | "as" | "default" | "define" | "enumeration" | "extends"
                | "for" | "import" | "major" | "model" | "namespace" | "optional"
                | "package" | "specification" | "struct" | "typeCollection"

fd_specification: "specification" fd_fqn ("extends" fd_fqn+)? "{" fd_host_decl* "}"
fd_host_decl: "for" SIMPLE_NAME "{" fd_parameter_decl* "}"
fd_parameter_decl: fd_valid_id ":" fd_type_ref ("(" fd_parameter_liability ("," fd_parameter_liability)* ")")? ";"
fd_parameter_liability: "optional" | ("default" ":" fd_complex_value)

fd_type_ref: (fd_predefined_type | fd_enum_type | fd_extension_type) FD_ARRAY_MARKER?
fd_predefined_type: FD_PREDEFINED_TYPE
fd_enum_type: "{" fd_valid_id ("," fd_valid_id)* "}"
fd_extension_type: fd_valid_id

FD_ARRAY_MARKER: "[]"
FD_PREDEFINED_TYPE.1: "Integer" | "String" | "Boolean" | "Interface"

?fd_complex_value: fd_value | fd_value_array
fd_value_array: "{" fd_value ("," fd_value)* "}"
fd_value: E_BIGINTEGER -> integer
        | ESCAPED_STRING -> string
        | E_BOOLEAN -> boolean
        | fd_valid_id

fd_types: "define" fd_fqn "for" "typeCollection" fd_fqn ("major" E_INTEGER)? ("as" fd_fqn)? "{" fd_use_definition* fd_parameter* fd_type_definition* "}"
fd_use_definition: "use" fd_fqn
fd_type_definition: fd_struct | fd_union | fd_type_def | fd_array | fd_enumeration | fd_map
fd_struct: "struct" fd_valid_id "{" fd_parameter_value* fd_field* "}"
fd_union: "union" fd_valid_id "{" fd_parameter_value* fd_field* "}"
fd_type_def: "typedef" fd_valid_id "{" fd_parameter* "}"
fd_field: fd_valid_id "{" fd_parameter* fd_type_overwrites? "}"
fd_array: "array" fd_valid_id "{" fd_parameter* fd_type_overwrites? "}"
fd_enumeration: "enumeration" fd_valid_id "{" fd_parameter_value* fd_enum_value* "}"
fd_parameter_value: fd_parameter ","?
fd_enum_value: fd_valid_id "{" fd_parameter* "}"
fd_map: "map" fd_valid_id "{" fd_parameter* fd_map_key? fd_map_value? "}"
fd_map_key: "key" "{" fd_parameter* "}"
fd_map_value: "value" "{" fd_parameter* "}"
fd_type_overwrites: "#" fd_plain_type_overwrites | "#struct" fd_struct_overwrites | "#union" fd_union_overwrites | "#enumeration" fd_enumeration_overwrites
fd_plain_type_overwrites: "{" fd_parameter* "}"
fd_struct_overwrites: "{" fd_parameter_value* fd_field* "}"
fd_union_overwrites: "{" fd_parameter_value* fd_field* "}"
fd_enumeration_overwrites: "{" fd_parameter_value* fd_enum_value* "}"
fd_parameter: fd_valid_id "=" fd_complex_value

%import .franca_com (_import, _imported_fqn, _fully_qualified_name, _valid_id, f_import_uri, E_INTEGER, E_BIGINTEGER, E_BOOLEAN, ESCAPED_STRING, SIMPLE_NAME, WS, CPP_COMMENT, C_COMMENT)
%ignore WS
%ignore CPP_COMMENT
%ignore C_COMMENT
