# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

filegroup(
    name = "ipc",
    srcs = [
        "score_architecture_deployment_spec.fdepl",
        "score_network_IPC_deployment_spec.fdepl",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "someip",
    srcs = [
        "score_architecture_deployment_spec.fdepl",
        "score_network_SOMEIP_deployment_spec.fdepl",
        "score_network_ethernet_deployment_spec.cdepl",
    ],
    visibility = ["//visibility:public"],
)
